### Test 1: Petición a las 10:00 del día 14 del producto 35455 para la brand 1 (ZARA)
GET http://localhost:8080/api/prices?productId=35455&brandId=1&applicationDate=2020-06-14T10:00:00

### Test 2: Petición a las 16:00 del día 14 del producto 35455 para la brand 1 (ZARA)
GET http://localhost:8080/api/prices?productId=35455&brandId=1&applicationDate=2020-06-14T16:00:00

### Test 3: Petición a las 21:00 del día 14 del producto 35455 para la brand 1 (ZARA)
GET http://localhost:8080/api/prices?productId=35455&brandId=1&applicationDate=2020-06-14T21:00:00

### Test 4: Petición a las 10:00 del día 15 del producto 35455 para la brand 1 (ZARA)
GET http://localhost:8080/api/prices?productId=35455&brandId=1&applicationDate=2020-06-15T10:00:00

### Test 5: Petición a las 21:00 del día 16 del producto 35455 para la brand 1 (ZARA)
GET http://localhost:8080/api/prices?productId=35455&brandId=1&applicationDate=2020-06-16T21:00:00
